from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets

from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, EmailStr, Field


def _utc_now() -> datetime:
    """Return current time in UTC."""
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    """Format datetime as ISO string."""
    return dt.astimezone(timezone.utc).isoformat()


def _b64url_encode(raw: bytes) -> str:
    """Base64-url encode without padding."""
    return base64.urlsafe_b64encode(raw).decode("utf-8").rstrip("=")


def _b64url_decode(data: str) -> bytes:
    """Base64-url decode with automatic padding."""
    padding = "=" * (-len(data) % 4)
    return base64.urlsafe_b64decode((data + padding).encode("utf-8"))


def _sign(data: bytes, secret: str) -> bytes:
    """HMAC-SHA256 signature."""
    return hmac.new(secret.encode("utf-8"), data, hashlib.sha256).digest()


def _get_auth_secret() -> str:
    """
    Get auth secret for signing tokens.

    NOTE: For a real deployment, set a strong secret via env var.
    We default to a random-per-process secret to avoid hardcoding.
    """
    # This is intentionally not persisted; tokens will reset on restart.
    # If you need persistent sessions, add AUTH_SECRET to .env.
    return os.environ.get("AUTH_SECRET", _IN_MEMORY_STATE.auth_secret)


def _hash_password(password: str, salt: str) -> str:
    """Hash a password using PBKDF2-HMAC-SHA256."""
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 200_000)
    return _b64url_encode(dk)


def _verify_password(password: str, salt: str, password_hash: str) -> bool:
    """Verify password against stored hash."""
    return hmac.compare_digest(_hash_password(password, salt), password_hash)


def _create_token(user_id: str, email: str, ttl_minutes: int = 60 * 24) -> str:
    """
    Create a lightweight signed bearer token (JWT-like) without external deps.

    Token format: base64url(payload_json) + "." + base64url(signature)
    Where signature = HMAC(secret, payload_b64)
    """
    exp = int((_utc_now() + timedelta(minutes=ttl_minutes)).timestamp())
    payload = f'{{"sub":"{user_id}","email":"{email}","exp":{exp}}}'.encode("utf-8")
    payload_b64 = _b64url_encode(payload).encode("utf-8")
    sig = _sign(payload_b64, _get_auth_secret())
    return f"{payload_b64.decode('utf-8')}.{_b64url_encode(sig)}"


def _decode_token(token: str) -> Dict[str, Any]:
    """Validate and decode the lightweight bearer token."""
    try:
        payload_b64, sig_b64 = token.split(".", 1)
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token format") from e

    expected_sig = _sign(payload_b64.encode("utf-8"), _get_auth_secret())
    try:
        provided_sig = _b64url_decode(sig_b64)
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token signature") from e

    if not hmac.compare_digest(expected_sig, provided_sig):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token signature")

    try:
        payload_raw = _b64url_decode(payload_b64).decode("utf-8")
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload") from e

    # Minimal JSON parsing (payload is generated by us); keep strict.
    # Example: {"sub":"...","email":"...","exp":123}
    if not payload_raw.startswith("{") or not payload_raw.endswith("}"):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload")

    # Very small parser to avoid adding dependencies.
    def _get_str(field: str) -> str:
        marker = f'"{field}":"'
        start = payload_raw.find(marker)
        if start == -1:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload")
        start += len(marker)
        end = payload_raw.find('"', start)
        if end == -1:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload")
        return payload_raw[start:end]

    def _get_int(field: str) -> int:
        marker = f'"{field}":'
        start = payload_raw.find(marker)
        if start == -1:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload")
        start += len(marker)
        end = payload_raw.find(",", start)
        if end == -1:
            end = payload_raw.find("}", start)
        if end == -1:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload")
        return int(payload_raw[start:end].strip())

    sub = _get_str("sub")
    email = _get_str("email")
    exp = _get_int("exp")

    now = int(_utc_now().timestamp())
    if now >= exp:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token expired")

    return {"sub": sub, "email": email, "exp": exp}


class _InMemoryState:
    """Simple in-memory persistence layer for demo use."""

    def __init__(self) -> None:
        self.auth_secret = secrets.token_urlsafe(48)

        # Users: user_id -> user record
        self.users: Dict[str, Dict[str, Any]] = {}
        # email -> user_id
        self.user_by_email: Dict[str, str] = {}

        # Products: product_id -> product record
        self.products: Dict[str, Dict[str, Any]] = {}

        # Affiliate click events
        self.affiliate_clicks: List[Dict[str, Any]] = []

        # Carts: user_id -> {product_id -> qty}
        self.carts: Dict[str, Dict[str, int]] = {}

        # Orders: user_id -> list[order]
        self.orders: Dict[str, List[Dict[str, Any]]] = {}

        # Rewards: user_id -> dict
        self.rewards: Dict[str, Dict[str, Any]] = {}

        self._seed()

    def _seed(self) -> None:
        """Seed products and a demo user."""
        products = [
            {
                "id": "p-heatless-curls",
                "title": "Heatless Curling Rod Headband",
                "description": "Viral no-heat curls kit for overnight waves.",
                "price": 12.99,
                "currency": "USD",
                "image_url": "https://picsum.photos/seed/curls/600/600",
                "category": "Beauty",
                "tags": ["viral", "beauty", "hair"],
                "rating": 4.6,
                "affiliate_url": "https://outletweb.shop/products/heatless-curling-rod",
                "is_trending": True,
            },
            {
                "id": "p-mini-printer",
                "title": "Pocket Thermal Mini Printer",
                "description": "Print notes, labels, and stickers from your phone.",
                "price": 29.99,
                "currency": "USD",
                "image_url": "https://picsum.photos/seed/printer/600/600",
                "category": "Gadgets",
                "tags": ["viral", "study", "gadgets"],
                "rating": 4.4,
                "affiliate_url": "https://outletweb.shop/products/mini-thermal-printer",
                "is_trending": True,
            },
            {
                "id": "p-led-strip",
                "title": "RGB LED Strip Lights (5m)",
                "description": "App-controlled room glow with music sync.",
                "price": 15.5,
                "currency": "USD",
                "image_url": "https://picsum.photos/seed/led/600/600",
                "category": "Home",
                "tags": ["room", "decor", "viral"],
                "rating": 4.2,
                "affiliate_url": "https://outletweb.shop/products/rgb-led-strip",
                "is_trending": False,
            },
        ]
        for p in products:
            self.products[p["id"]] = p

        # Demo user
        demo_email = "demo@viraltrend.local"
        demo_password = "demo12345"
        self._create_user(email=demo_email, password=demo_password, display_name="Demo User")

    def _create_user(self, email: str, password: str, display_name: str) -> Dict[str, Any]:
        user_id = f"u-{secrets.token_urlsafe(8)}"
        salt = secrets.token_urlsafe(16)
        record = {
            "id": user_id,
            "email": email.lower(),
            "display_name": display_name,
            "password_salt": salt,
            "password_hash": _hash_password(password, salt),
            "created_at": _iso(_utc_now()),
        }
        self.users[user_id] = record
        self.user_by_email[email.lower()] = user_id

        # Initialize rewards
        self.rewards[user_id] = {
            "user_id": user_id,
            "points_balance": 0,
            "tier": "Bronze",
            "history": [],
            "updated_at": _iso(_utc_now()),
        }
        return record


_IN_MEMORY_STATE = _InMemoryState()


class Tier(str, Enum):
    bronze = "Bronze"
    silver = "Silver"
    gold = "Gold"
    platinum = "Platinum"


def _tier_for_points(points: int) -> Tier:
    if points >= 5000:
        return Tier.platinum
    if points >= 2000:
        return Tier.gold
    if points >= 500:
        return Tier.silver
    return Tier.bronze


def _ensure_rewards(user_id: str) -> Dict[str, Any]:
    if user_id not in _IN_MEMORY_STATE.rewards:
        _IN_MEMORY_STATE.rewards[user_id] = {
            "user_id": user_id,
            "points_balance": 0,
            "tier": Tier.bronze.value,
            "history": [],
            "updated_at": _iso(_utc_now()),
        }
    return _IN_MEMORY_STATE.rewards[user_id]


def _add_points(user_id: str, delta: int, reason: str, meta: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    rewards = _ensure_rewards(user_id)
    old_points = int(rewards.get("points_balance", 0))
    new_points = max(0, old_points + delta)
    rewards["points_balance"] = new_points
    rewards["tier"] = _tier_for_points(new_points).value
    rewards["updated_at"] = _iso(_utc_now())
    rewards["history"].insert(
        0,
        {
            "id": f"rh-{secrets.token_urlsafe(6)}",
            "timestamp": _iso(_utc_now()),
            "delta": delta,
            "reason": reason,
            "meta": meta or {},
            "balance_after": new_points,
        },
    )
    return rewards


# -----------------------------
# API models
# -----------------------------
class HealthResponse(BaseModel):
    message: str = Field(..., description="Health status message")


class ErrorResponse(BaseModel):
    detail: str = Field(..., description="Error message")


class SignUpRequest(BaseModel):
    email: EmailStr = Field(..., description="User email")
    password: str = Field(..., min_length=6, description="User password (min 6 chars)")
    display_name: str = Field(..., min_length=1, max_length=50, description="Display name")


class LoginRequest(BaseModel):
    email: EmailStr = Field(..., description="User email")
    password: str = Field(..., min_length=1, description="User password")


class AuthResponse(BaseModel):
    access_token: str = Field(..., description="Bearer token to use in Authorization header")
    token_type: str = Field("bearer", description="Token type")
    user: Dict[str, Any] = Field(..., description="User profile summary")


class MeResponse(BaseModel):
    id: str = Field(..., description="User id")
    email: EmailStr = Field(..., description="User email")
    display_name: str = Field(..., description="Display name")
    created_at: str = Field(..., description="ISO timestamp")


class Product(BaseModel):
    id: str = Field(..., description="Product id")
    title: str = Field(..., description="Product title")
    description: str = Field(..., description="Product description")
    price: float = Field(..., ge=0, description="Unit price")
    currency: str = Field("USD", description="Currency code")
    image_url: str = Field(..., description="Image URL")
    category: str = Field(..., description="Category")
    tags: List[str] = Field(default_factory=list, description="Tags")
    rating: float = Field(0, ge=0, le=5, description="Average rating")
    affiliate_url: str = Field(..., description="Destination affiliate URL")
    is_trending: bool = Field(False, description="Whether product is currently trending")


class ProductListResponse(BaseModel):
    items: List[Product] = Field(..., description="List of products")
    total: int = Field(..., description="Total count")
    page: int = Field(..., description="Current page (1-based)")
    page_size: int = Field(..., description="Page size")


class CartItem(BaseModel):
    product_id: str = Field(..., description="Product id")
    quantity: int = Field(..., ge=1, le=99, description="Quantity")


class CartResponse(BaseModel):
    user_id: str = Field(..., description="User id")
    items: List[CartItem] = Field(..., description="Cart items")
    subtotal: float = Field(..., ge=0, description="Subtotal price (sum of item price * qty)")
    currency: str = Field("USD", description="Currency")


class CartUpdateRequest(BaseModel):
    items: List[CartItem] = Field(..., description="Replace cart with these items")


class CheckoutRequest(BaseModel):
    # Mock checkout: collect shipping + payment method summary (no real payment)
    shipping_name: str = Field(..., min_length=1, description="Recipient name")
    shipping_address: str = Field(..., min_length=1, description="Shipping address")
    payment_method: str = Field(..., min_length=1, description="Payment method label (mock)")
    affiliate_ref: Optional[str] = Field(None, description="Optional affiliate ref used at checkout")


class CheckoutResponse(BaseModel):
    order_id: str = Field(..., description="Generated order id")
    status: str = Field(..., description="Order status")
    total: float = Field(..., ge=0, description="Total amount")
    currency: str = Field("USD", description="Currency")
    awarded_points: int = Field(..., ge=0, description="Points awarded for this order")
    new_points_balance: int = Field(..., ge=0, description="Updated points balance")


class RewardsSummaryResponse(BaseModel):
    user_id: str = Field(..., description="User id")
    points_balance: int = Field(..., ge=0, description="Current points balance")
    tier: Tier = Field(..., description="Current tier")
    updated_at: str = Field(..., description="ISO timestamp")


class RewardsHistoryItem(BaseModel):
    id: str = Field(..., description="History entry id")
    timestamp: str = Field(..., description="ISO timestamp")
    delta: int = Field(..., description="Points delta (+/-)")
    reason: str = Field(..., description="Why points changed")
    meta: Dict[str, Any] = Field(default_factory=dict, description="Extra metadata")
    balance_after: int = Field(..., ge=0, description="Balance after applying delta")


class RewardsHistoryResponse(BaseModel):
    user_id: str = Field(..., description="User id")
    items: List[RewardsHistoryItem] = Field(..., description="History entries (most recent first)")


class AffiliateTrackResponse(BaseModel):
    click_id: str = Field(..., description="Recorded click id")
    product_id: str = Field(..., description="Product id")
    destination: str = Field(..., description="Affiliate destination URL")
    created_at: str = Field(..., description="ISO timestamp")


# -----------------------------
# Auth dependencies
# -----------------------------
# PUBLIC_INTERFACE
def get_current_user(authorization: Optional[str] = Header(None)) -> Dict[str, Any]:
    """Resolve current user from Authorization: Bearer <token> header."""
    if not authorization:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Missing Authorization header")

    parts = authorization.split(" ", 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid Authorization header")

    token = parts[1].strip()
    decoded = _decode_token(token)
    user_id = decoded["sub"]
    user = _IN_MEMORY_STATE.users.get(user_id)
    if not user:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")
    return user


def _cart_totals(cart_map: Dict[str, int]) -> Tuple[List[CartItem], float, str]:
    items: List[CartItem] = []
    subtotal = 0.0
    currency = "USD"
    for pid, qty in cart_map.items():
        product = _IN_MEMORY_STATE.products.get(pid)
        if not product:
            continue
        items.append(CartItem(product_id=pid, quantity=qty))
        subtotal += float(product["price"]) * int(qty)
        currency = product.get("currency", "USD") or "USD"
    return items, round(subtotal, 2), currency


# -----------------------------
# App setup
# -----------------------------
openapi_tags = [
    {"name": "Health", "description": "Health and diagnostics endpoints"},
    {"name": "Auth", "description": "Signup/login and user profile"},
    {"name": "Products", "description": "Trending products catalog"},
    {"name": "Affiliate", "description": "Affiliate click tracking and redirect"},
    {"name": "Cart", "description": "Cart CRUD"},
    {"name": "Checkout", "description": "Mock checkout / order creation"},
    {"name": "Rewards", "description": "Points, tiers, and rewards history"},
    {"name": "Docs", "description": "Documentation helper endpoints"},
]

app = FastAPI(
    title="ViralTrend Connect API",
    description=(
        "Backend API for ViralTrend Connect (demo).\n\n"
        "Includes auth, product catalog, affiliate click tracking + redirect, cart, "
        "mock checkout, and rewards/loyalty.\n\n"
        "Auth: Use `Authorization: Bearer <access_token>` obtained from `/auth/login`."
    ),
    version="1.0.0",
    openapi_tags=openapi_tags,
)

# CORS: default to allow any origin for template friendliness, but allow tightening via env var.
cors_origins_raw = os.environ.get("CORS_ALLOW_ORIGINS", "*")
allow_origins = ["*"] if cors_origins_raw.strip() == "*" else [o.strip() for o in cors_origins_raw.split(",") if o.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# -----------------------------
# Health / docs helpers
# -----------------------------
@app.get(
    "/",
    tags=["Health"],
    summary="Health check",
    response_model=HealthResponse,
    responses={500: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def health_check() -> HealthResponse:
    """Return basic health status."""
    return HealthResponse(message="Healthy")


@app.get(
    "/docs/usage",
    tags=["Docs"],
    summary="API usage notes",
    response_model=Dict[str, Any],
)
# PUBLIC_INTERFACE
def docs_usage() -> Dict[str, Any]:
    """Return quick usage notes for common flows (auth -> browse -> cart -> checkout -> rewards)."""
    return {
        "auth": {
            "signup": {"method": "POST", "path": "/auth/signup"},
            "login": {"method": "POST", "path": "/auth/login"},
            "me": {"method": "GET", "path": "/auth/me", "auth": "Bearer"},
        },
        "products": {"method": "GET", "path": "/products", "query": ["q", "category", "trending_only", "page", "page_size"]},
        "affiliate": {
            "track": {"method": "POST", "path": "/affiliate/track", "body": {"product_id": "p-..."}},
            "redirect": {"method": "GET", "path": "/affiliate/redirect?product_id=p-...&click_id=..."},
        },
        "cart": {
            "get": {"method": "GET", "path": "/cart", "auth": "Bearer"},
            "replace": {"method": "PUT", "path": "/cart", "auth": "Bearer"},
            "add_one": {"method": "POST", "path": "/cart/items", "auth": "Bearer"},
            "remove_one": {"method": "DELETE", "path": "/cart/items/{product_id}", "auth": "Bearer"},
        },
        "checkout": {"method": "POST", "path": "/checkout", "auth": "Bearer"},
        "rewards": {
            "summary": {"method": "GET", "path": "/rewards/summary", "auth": "Bearer"},
            "history": {"method": "GET", "path": "/rewards/history", "auth": "Bearer"},
        },
        "notes": [
            "This demo uses in-memory storage. Data resets on server restart.",
            "Affiliate tracking is recorded server-side and can be tied to checkout via affiliate_ref.",
        ],
    }


# -----------------------------
# Auth
# -----------------------------
@app.post(
    "/auth/signup",
    tags=["Auth"],
    summary="Create an account",
    response_model=AuthResponse,
    status_code=status.HTTP_201_CREATED,
    responses={400: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def auth_signup(payload: SignUpRequest) -> AuthResponse:
    """Create a user and return an access token."""
    email = payload.email.lower()
    if email in _IN_MEMORY_STATE.user_by_email:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Email already registered")

    user = _IN_MEMORY_STATE._create_user(email=email, password=payload.password, display_name=payload.display_name)
    token = _create_token(user_id=user["id"], email=user["email"])
    return AuthResponse(
        access_token=token,
        user={"id": user["id"], "email": user["email"], "display_name": user["display_name"], "created_at": user["created_at"]},
    )


@app.post(
    "/auth/login",
    tags=["Auth"],
    summary="Login with email/password",
    response_model=AuthResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def auth_login(payload: LoginRequest) -> AuthResponse:
    """Validate credentials and return an access token."""
    email = payload.email.lower()
    user_id = _IN_MEMORY_STATE.user_by_email.get(email)
    if not user_id:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid email or password")

    user = _IN_MEMORY_STATE.users[user_id]
    if not _verify_password(payload.password, user["password_salt"], user["password_hash"]):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid email or password")

    token = _create_token(user_id=user["id"], email=user["email"])
    return AuthResponse(
        access_token=token,
        user={"id": user["id"], "email": user["email"], "display_name": user["display_name"], "created_at": user["created_at"]},
    )


@app.get(
    "/auth/me",
    tags=["Auth"],
    summary="Get current user profile",
    response_model=MeResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def auth_me(user: Dict[str, Any] = Depends(get_current_user)) -> MeResponse:
    """Return the authenticated user's profile."""
    return MeResponse(id=user["id"], email=user["email"], display_name=user["display_name"], created_at=user["created_at"])


# -----------------------------
# Products
# -----------------------------
@app.get(
    "/products",
    tags=["Products"],
    summary="List products",
    response_model=ProductListResponse,
)
# PUBLIC_INTERFACE
def list_products(
    q: Optional[str] = Query(None, description="Search query on title/description"),
    category: Optional[str] = Query(None, description="Filter by category"),
    trending_only: bool = Query(False, description="Only return trending items"),
    page: int = Query(1, ge=1, description="Page number (1-based)"),
    page_size: int = Query(24, ge=1, le=100, description="Items per page"),
) -> ProductListResponse:
    """Return a paginated list of products with optional filters."""
    items = list(_IN_MEMORY_STATE.products.values())

    if trending_only:
        items = [p for p in items if bool(p.get("is_trending"))]

    if category:
        items = [p for p in items if str(p.get("category", "")).lower() == category.lower()]

    if q:
        ql = q.lower()
        items = [
            p
            for p in items
            if ql in str(p.get("title", "")).lower() or ql in str(p.get("description", "")).lower() or ql in " ".join(p.get("tags", [])).lower()
        ]

    total = len(items)
    start = (page - 1) * page_size
    end = start + page_size
    paged = items[start:end]
    return ProductListResponse(items=[Product(**p) for p in paged], total=total, page=page, page_size=page_size)


@app.get(
    "/products/{product_id}",
    tags=["Products"],
    summary="Get a product by id",
    response_model=Product,
    responses={404: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def get_product(product_id: str) -> Product:
    """Fetch a single product."""
    product = _IN_MEMORY_STATE.products.get(product_id)
    if not product:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")
    return Product(**product)


# -----------------------------
# Affiliate tracking / redirect
# -----------------------------
@app.post(
    "/affiliate/track",
    tags=["Affiliate"],
    summary="Track an affiliate click",
    response_model=AffiliateTrackResponse,
    responses={404: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def affiliate_track(
    request: Request,
    product_id: str = Query(..., description="Product id to track click for"),
    ref: Optional[str] = Query(None, description="Optional affiliate ref code"),
) -> AffiliateTrackResponse:
    """
    Record an affiliate click event (server-side).

    Client can then call `/affiliate/redirect` to actually redirect the user.
    """
    product = _IN_MEMORY_STATE.products.get(product_id)
    if not product:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")

    click_id = f"clk-{secrets.token_urlsafe(8)}"
    ev = {
        "click_id": click_id,
        "product_id": product_id,
        "destination": product["affiliate_url"],
        "ref": ref,
        "ua": request.headers.get("user-agent"),
        "ip": request.client.host if request.client else None,
        "created_at": _iso(_utc_now()),
    }
    _IN_MEMORY_STATE.affiliate_clicks.append(ev)

    return AffiliateTrackResponse(click_id=click_id, product_id=product_id, destination=product["affiliate_url"], created_at=ev["created_at"])


@app.get(
    "/affiliate/redirect",
    tags=["Affiliate"],
    summary="Redirect to the affiliate URL",
    responses={
        307: {"description": "Temporary Redirect"},
        404: {"model": ErrorResponse},
    },
)
# PUBLIC_INTERFACE
def affiliate_redirect(
    request: Request,
    product_id: str = Query(..., description="Product id"),
    click_id: Optional[str] = Query(None, description="Optional click id from /affiliate/track"),
    ref: Optional[str] = Query(None, description="Optional affiliate ref code"),
) -> Response:
    """
    Redirect the user to the affiliate URL and record the click (if not already tracked).

    This is a GET endpoint suitable for link-outs from the UI.
    """
    product = _IN_MEMORY_STATE.products.get(product_id)
    if not product:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")

    destination = product["affiliate_url"]

    # If click_id is not provided, create a new click record.
    if not click_id:
        click_id = f"clk-{secrets.token_urlsafe(8)}"
        ev = {
            "click_id": click_id,
            "product_id": product_id,
            "destination": destination,
            "ref": ref,
            "ua": request.headers.get("user-agent"),
            "ip": request.client.host if request.client else None,
            "created_at": _iso(_utc_now()),
        }
        _IN_MEMORY_STATE.affiliate_clicks.append(ev)

    return RedirectResponse(url=destination, status_code=status.HTTP_307_TEMPORARY_REDIRECT)


# -----------------------------
# Cart
# -----------------------------
@app.get(
    "/cart",
    tags=["Cart"],
    summary="Get current user's cart",
    response_model=CartResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def get_cart(user: Dict[str, Any] = Depends(get_current_user)) -> CartResponse:
    """Return cart contents for the current user."""
    cart_map = _IN_MEMORY_STATE.carts.get(user["id"], {})
    items, subtotal, currency = _cart_totals(cart_map)
    return CartResponse(user_id=user["id"], items=items, subtotal=subtotal, currency=currency)


@app.put(
    "/cart",
    tags=["Cart"],
    summary="Replace current user's cart",
    response_model=CartResponse,
    responses={400: {"model": ErrorResponse}, 401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def replace_cart(payload: CartUpdateRequest, user: Dict[str, Any] = Depends(get_current_user)) -> CartResponse:
    """Replace entire cart for the current user."""
    cart_map: Dict[str, int] = {}
    for it in payload.items:
        if it.product_id not in _IN_MEMORY_STATE.products:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Unknown product_id: {it.product_id}")
        cart_map[it.product_id] = it.quantity

    _IN_MEMORY_STATE.carts[user["id"]] = cart_map
    items, subtotal, currency = _cart_totals(cart_map)
    return CartResponse(user_id=user["id"], items=items, subtotal=subtotal, currency=currency)


@app.post(
    "/cart/items",
    tags=["Cart"],
    summary="Add/update a single cart item",
    response_model=CartResponse,
    responses={400: {"model": ErrorResponse}, 401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def upsert_cart_item(payload: CartItem, user: Dict[str, Any] = Depends(get_current_user)) -> CartResponse:
    """Upsert a single product quantity in cart."""
    if payload.product_id not in _IN_MEMORY_STATE.products:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unknown product_id")

    cart_map = _IN_MEMORY_STATE.carts.setdefault(user["id"], {})
    cart_map[payload.product_id] = payload.quantity
    items, subtotal, currency = _cart_totals(cart_map)
    return CartResponse(user_id=user["id"], items=items, subtotal=subtotal, currency=currency)


@app.delete(
    "/cart/items/{product_id}",
    tags=["Cart"],
    summary="Remove an item from cart",
    response_model=CartResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def remove_cart_item(product_id: str, user: Dict[str, Any] = Depends(get_current_user)) -> CartResponse:
    """Remove a product from cart (no-op if not present)."""
    cart_map = _IN_MEMORY_STATE.carts.setdefault(user["id"], {})
    cart_map.pop(product_id, None)
    items, subtotal, currency = _cart_totals(cart_map)
    return CartResponse(user_id=user["id"], items=items, subtotal=subtotal, currency=currency)


# -----------------------------
# Checkout (mock)
# -----------------------------
@app.post(
    "/checkout",
    tags=["Checkout"],
    summary="Create a mock order from the current cart",
    response_model=CheckoutResponse,
    responses={400: {"model": ErrorResponse}, 401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def checkout(payload: CheckoutRequest, user: Dict[str, Any] = Depends(get_current_user)) -> CheckoutResponse:
    """
    Mock checkout:
    - Validates cart not empty
    - Creates an order record
    - Clears cart
    - Awards loyalty points based on order total
    """
    cart_map = _IN_MEMORY_STATE.carts.get(user["id"], {})
    items, subtotal, currency = _cart_totals(cart_map)
    if not items:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Cart is empty")

    order_id = f"ord-{secrets.token_urlsafe(10)}"
    created_at = _iso(_utc_now())

    order = {
        "order_id": order_id,
        "user_id": user["id"],
        "created_at": created_at,
        "status": "confirmed",
        "items": [it.model_dump() for it in items],
        "subtotal": subtotal,
        "currency": currency,
        "shipping": {"name": payload.shipping_name, "address": payload.shipping_address},
        "payment_method": payload.payment_method,
        "affiliate_ref": payload.affiliate_ref,
    }
    _IN_MEMORY_STATE.orders.setdefault(user["id"], []).insert(0, order)

    # Clear cart
    _IN_MEMORY_STATE.carts[user["id"]] = {}

    # Award points: 10 points per $1 (rounded down), min 10 points
    awarded = max(10, int(subtotal * 10))
    rewards = _add_points(
        user_id=user["id"],
        delta=awarded,
        reason="purchase",
        meta={"order_id": order_id, "subtotal": subtotal, "currency": currency, "affiliate_ref": payload.affiliate_ref},
    )

    return CheckoutResponse(
        order_id=order_id,
        status=order["status"],
        total=subtotal,
        currency=currency,
        awarded_points=awarded,
        new_points_balance=int(rewards["points_balance"]),
    )


# -----------------------------
# Rewards / loyalty
# -----------------------------
@app.get(
    "/rewards/summary",
    tags=["Rewards"],
    summary="Get current user's rewards summary",
    response_model=RewardsSummaryResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def rewards_summary(user: Dict[str, Any] = Depends(get_current_user)) -> RewardsSummaryResponse:
    """Return points balance and tier for current user."""
    rewards = _ensure_rewards(user["id"])
    return RewardsSummaryResponse(
        user_id=user["id"],
        points_balance=int(rewards["points_balance"]),
        tier=Tier(rewards["tier"]),
        updated_at=rewards["updated_at"],
    )


@app.get(
    "/rewards/history",
    tags=["Rewards"],
    summary="Get current user's rewards history",
    response_model=RewardsHistoryResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def rewards_history(
    user: Dict[str, Any] = Depends(get_current_user),
    limit: int = Query(50, ge=1, le=200, description="Max entries to return"),
) -> RewardsHistoryResponse:
    """Return rewards history entries (most recent first)."""
    rewards = _ensure_rewards(user["id"])
    items = rewards.get("history", [])[:limit]
    return RewardsHistoryResponse(user_id=user["id"], items=[RewardsHistoryItem(**it) for it in items])


@app.post(
    "/rewards/earn",
    tags=["Rewards"],
    summary="Earn points (demo helper)",
    response_model=RewardsSummaryResponse,
    responses={401: {"model": ErrorResponse}},
)
# PUBLIC_INTERFACE
def rewards_earn(
    user: Dict[str, Any] = Depends(get_current_user),
    points: int = Query(50, ge=1, le=1000, description="Points to earn"),
    reason: str = Query("engagement", min_length=1, description="Reason for earning points"),
) -> RewardsSummaryResponse:
    """
    Demo helper to add points for engagement actions (e.g., daily check-in, share, review).

    This is useful for UI flows that demonstrate loyalty progression without payment.
    """
    rewards = _add_points(user_id=user["id"], delta=points, reason=reason, meta={"source": "demo"})
    return RewardsSummaryResponse(
        user_id=user["id"],
        points_balance=int(rewards["points_balance"]),
        tier=Tier(rewards["tier"]),
        updated_at=rewards["updated_at"],
    )
